In [9]:
import pandas as pd
from sqlalchemy import create_engine
url = "https://docs.google.com/spreadsheets/d/1l2YtEEMkziLTuo3G0C5eJcXPGYXfA95W3KOw52cslfo/export?format=csv&id"
influenza_df = pd.read_csv(url)
influenza_df.columns

Index(['Country', 'WHOREGION', 'FLUREGION', 'Year', 'Week', 'SDATE', 'EDATE',
       'SPEC_RECEIVED_NB', 'SPEC_PROCESSED_NB', 'AH1', 'AH1N12009', 'AH3',
       'AH5', 'ANOTSUBTYPED', 'INF_A', 'BYAMAGATA', 'BVICTORIA',
       'BNOTDETERMINED', 'INF_B', 'ALL_INF', 'ALL_INF2', 'TITLE'],
      dtype='object')

In [12]:
influenza_df2 = influenza_df[["Country","Year","SDATE","EDATE","SPEC_PROCESSED_NB",\
                                ]].copy()
influenza_df2.head

<bound method NDFrame.head of           Country  Year       SDATE       EDATE  SPEC_PROCESSED_NB
0     Afghanistan  2019  2018-12-31  2019-01-06               52.0
1     Afghanistan  2019  2019-01-07  2019-01-13               74.0
2     Afghanistan  2019  2019-01-14  2019-01-20               99.0
3     Afghanistan  2019  2019-01-21  2019-01-27              116.0
4     Afghanistan  2019  2019-01-28  2019-02-03              111.0
5     Afghanistan  2019  2019-02-04  2019-02-10               75.0
6     Afghanistan  2019  2019-02-11  2019-02-17               82.0
7     Afghanistan  2019  2019-02-18  2019-02-24               93.0
8     Afghanistan  2019  2019-02-25  2019-03-03              114.0
9     Afghanistan  2019  2019-03-04  2019-03-10               89.0
10    Afghanistan  2019  2019-03-11  2019-03-17               60.0
11    Afghanistan  2019  2019-03-18  2019-03-24               79.0
12    Afghanistan  2019  2019-03-25  2019-03-31              111.0
13    Afghanistan  2019  2019-04-01  2019-04-07               50.0
14    Afghanistan  2019  2019-04-08  2019-04-14               56.0
15    Afghanistan  2019  2019-04-15  2019-04-21               94.0
16    Afghanistan  2019  2019-04-22  2019-04-28               43.0
17    Afghanistan  2019  2019-04-29  2019-05-05               52.0
18    Afghanistan  2019  2019-05-06  2019-05-12               54.0
19    Afghanistan  2019  2019-05-13  2019-05-19               27.0
20    Afghanistan  2019  2019-05-20  2019-05-26               54.0
21    Afghanistan  2019  2019-05-27  2019-06-02               40.0
22    Afghanistan  2019  2019-06-03  2019-06-09               15.0
23    Afghanistan  2019  2019-06-10  2019-06-16               52.0
24    Afghanistan  2019  2019-06-17  2019-06-23               52.0
25    Afghanistan  2019  2019-06-24  2019-06-30               40.0
26    Afghanistan  2019  2019-07-01  2019-07-07               44.0
27    Afghanistan  2019  2019-07-08  2019-07-14               38.0
28    Afghanistan  2019  2019-07-15  2019-07-21               38.0
29    Afghanistan  2019  2019-07-22  2019-07-28               49.0
...           ...   ...         ...         ...                ...
7488       Zambia  2019  2019-07-15  2019-07-21               58.0
7489       Zambia  2019  2019-07-22  2019-07-28               65.0
7490       Zambia  2019  2019-07-29  2019-08-04               71.0
7491       Zambia  2019  2019-08-05  2019-08-11               68.0
7492       Zambia  2019  2019-08-12  2019-08-18               66.0
7493       Zambia  2019  2019-08-19  2019-08-25               81.0
7494       Zambia  2019  2019-08-26  2019-09-01               38.0
7495       Zambia  2019  2019-09-02  2019-09-08               76.0
7496       Zambia  2019  2019-09-09  2019-09-15               75.0
7497       Zambia  2019  2019-09-16  2019-09-22               74.0
7498       Zambia  2019  2019-09-23  2019-09-29               70.0
7499       Zambia  2019  2019-09-30  2019-10-06               58.0
7500       Zambia  2019  2019-10-07  2019-10-13               62.0
7501       Zambia  2019  2019-10-14  2019-10-20               50.0
7502       Zambia  2019  2019-10-21  2019-10-27               51.0
7503       Zambia  2019  2019-10-28  2019-11-03               49.0
7504       Zambia  2019  2019-11-04  2019-11-10               60.0
7505       Zambia  2019  2019-11-11  2019-11-17               37.0
7506       Zambia  2019  2019-11-18  2019-11-24               53.0
7507       Zambia  2019  2019-11-25  2019-12-01               62.0
7508       Zambia  2019  2019-12-02  2019-12-08               47.0
7509       Zambia  2019  2019-12-09  2019-12-15               50.0
7510       Zambia  2019  2019-12-16  2019-12-22               47.0
7511       Zambia  2019  2019-12-23  2019-12-29               43.0
7512       Zambia  2020  2019-12-30  2020-01-05                0.0
7513       Zambia  2020  2020-01-06  2020-01-12                6.0
7514       Zambia  2020  2020-01-13  2020-01-19               16.0
7515       Zambia  2020  2020-01-20  2020-01-26                6.0
7516       Zambia  2020  2020-01-27  2020-02-02                0.0
7517       Zambia  2020  2020-02-03  2020-02-09                0.0

[7518 rows x 5 columns]>

In [16]:
influenza_df2.rename(columns = {"SPEC_PROCESSED_NB":"Number of Cases", "SDATE":"Start Date", "EDATE":"End Date"}, inplace=True)
influenza_df2

          Country  Year  Start Date    End Date  Number of Cases
0     Afghanistan  2019  2018-12-31  2019-01-06             52.0
1     Afghanistan  2019  2019-01-07  2019-01-13             74.0
2     Afghanistan  2019  2019-01-14  2019-01-20             99.0
3     Afghanistan  2019  2019-01-21  2019-01-27            116.0
4     Afghanistan  2019  2019-01-28  2019-02-03            111.0
5     Afghanistan  2019  2019-02-04  2019-02-10             75.0
6     Afghanistan  2019  2019-02-11  2019-02-17             82.0
7     Afghanistan  2019  2019-02-18  2019-02-24             93.0
8     Afghanistan  2019  2019-02-25  2019-03-03            114.0
9     Afghanistan  2019  2019-03-04  2019-03-10             89.0
10    Afghanistan  2019  2019-03-11  2019-03-17             60.0
11    Afghanistan  2019  2019-03-18  2019-03-24             79.0
12    Afghanistan  2019  2019-03-25  2019-03-31            111.0
13    Afghanistan  2019  2019-04-01  2019-04-07             50.0
14    Afghanistan  2019  2019-04-08  2019-04-14             56.0
15    Afghanistan  2019  2019-04-15  2019-04-21             94.0
16    Afghanistan  2019  2019-04-22  2019-04-28             43.0
17    Afghanistan  2019  2019-04-29  2019-05-05             52.0
18    Afghanistan  2019  2019-05-06  2019-05-12             54.0
19    Afghanistan  2019  2019-05-13  2019-05-19             27.0
20    Afghanistan  2019  2019-05-20  2019-05-26             54.0
21    Afghanistan  2019  2019-05-27  2019-06-02             40.0
22    Afghanistan  2019  2019-06-03  2019-06-09             15.0
23    Afghanistan  2019  2019-06-10  2019-06-16             52.0
24    Afghanistan  2019  2019-06-17  2019-06-23             52.0
25    Afghanistan  2019  2019-06-24  2019-06-30             40.0
26    Afghanistan  2019  2019-07-01  2019-07-07             44.0
27    Afghanistan  2019  2019-07-08  2019-07-14             38.0
28    Afghanistan  2019  2019-07-15  2019-07-21             38.0
29    Afghanistan  2019  2019-07-22  2019-07-28             49.0
...           ...   ...         ...         ...              ...
7488       Zambia  2019  2019-07-15  2019-07-21             58.0
7489       Zambia  2019  2019-07-22  2019-07-28             65.0
7490       Zambia  2019  2019-07-29  2019-08-04             71.0
7491       Zambia  2019  2019-08-05  2019-08-11             68.0
7492       Zambia  2019  2019-08-12  2019-08-18             66.0
7493       Zambia  2019  2019-08-19  2019-08-25             81.0
7494       Zambia  2019  2019-08-26  2019-09-01             38.0
7495       Zambia  2019  2019-09-02  2019-09-08             76.0
7496       Zambia  2019  2019-09-09  2019-09-15             75.0
7497       Zambia  2019  2019-09-16  2019-09-22             74.0
7498       Zambia  2019  2019-09-23  2019-09-29             70.0
7499       Zambia  2019  2019-09-30  2019-10-06             58.0
7500       Zambia  2019  2019-10-07  2019-10-13             62.0
7501       Zambia  2019  2019-10-14  2019-10-20             50.0
7502       Zambia  2019  2019-10-21  2019-10-27             51.0
7503       Zambia  2019  2019-10-28  2019-11-03             49.0
7504       Zambia  2019  2019-11-04  2019-11-10             60.0
7505       Zambia  2019  2019-11-11  2019-11-17             37.0
7506       Zambia  2019  2019-11-18  2019-11-24             53.0
7507       Zambia  2019  2019-11-25  2019-12-01             62.0
7508       Zambia  2019  2019-12-02  2019-12-08             47.0
7509       Zambia  2019  2019-12-09  2019-12-15             50.0
7510       Zambia  2019  2019-12-16  2019-12-22             47.0
7511       Zambia  2019  2019-12-23  2019-12-29             43.0
7512       Zambia  2020  2019-12-30  2020-01-05              0.0
7513       Zambia  2020  2020-01-06  2020-01-12              6.0
7514       Zambia  2020  2020-01-13  2020-01-19             16.0
7515       Zambia  2020  2020-01-20  2020-01-26              6.0
7516       Zambia  2020  2020-01-27  2020-02-02              0.0
7517       Zambia  2020  2020-02-03  2020-02-09              0.0

[7518 rows x 5 columns]

In [25]:
influenza_df2["Country"] = influenza_df2["Country"].astype(str)
#convert all country names to strings

In [39]:
influenza_df2_byCountry = influenza_df2.groupby(by="Country").sum().drop(columns=["Year"])

influenza_df2_byCountry.sort_values(by="Number of Cases", ascending=False)
#This is the final Flu df

                                                    Number of Cases
Country
China                                                      769651.0
Canada                                                     386057.0
Norway                                                     227413.0
France                                                     177367.0
Russian Federation                                         139008.0
United States of America                                   117914.0
Australia                                                   97103.0
Argentina                                                   96202.0
United Kingdom of Great Britain and Northern Ir...          94668.0
Sweden                                                      94552.0
Denmark                                                     78818.0
Chile                                                       63082.0
Spain                                                       46037.0
Qatar                                                       42964.0
India                                                       39912.0
Mexico                                                      34396.0
Iran (Islamic Republic of)                                  29691.0
Portugal                                                    27468.0
Ireland                                                     27241.0
Italy                                                       25856.0
Slovenia                                                    22980.0
Brazil                                                      18934.0
Austria                                                     18645.0
Paraguay                                                    17527.0
Kuwait                                                      15693.0
Egypt                                                       14574.0
Colombia                                                    14202.0
Saudi Arabia                                                13775.0
Israel                                                      12651.0
Republic of Korea                                           12441.0
...                                                             ...
Fiji                                                          525.0
French Guiana                                                 506.0
Georgia                                                       495.0
Mauritania                                                    442.0
Finland                                                       437.0
Aruba                                                         366.0
Turkmenistan                                                  350.0
Martinique                                                    282.0
Barbados                                                      261.0
Algeria                                                       256.0
Venezuela (Bolivarian Republic of)                            212.0
South Sudan                                                   210.0
Tajikistan                                                    191.0
Uzbekistan                                                    170.0
Sierra Leone                                                  169.0
Guadeloupe                                                    167.0
Chad                                                          138.0
Papua New Guinea                                              134.0
Seychelles                                                     63.0
Saint Vincent and the Grenadines                               41.0
Dominica                                                       35.0
Saint Kitts and Nevis                                          32.0
Saint Lucia                                                    28.0
Turks and Caicos Is.                                           21.0
Bermuda                                                        12.0
Anguilla                                                        4.0
Bahamas                                                         2.0
Antigua and Barbuda                                             1.0
Bosnia and Herzegovina                                          0.0
Japan                                                           0.0

[158 rows x 1 columns]