In [1]:
import pandas as pd
import sqlalchemy
import numpy as np
import datetime
import re
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func
# from six.moves.urllib.request import urlopen
# import urllib
url ="https://docs.google.com/spreadsheets/d/1wzbUySCMjjRdDqBNsoE0byhYplVk8rLbK3Vq0nU0dFQ/export?format=csv&id"
data = pd.read_csv(url, error_bad_lines=False)
data

C:\Users\Dan\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3057: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,report_date,location,location_type,data_field,data_field_code,time_period,time_period_type,value,unit
0,2016-03-19,Argentina-Buenos_Aires,province,cumulative_confirmed_local_cases,AR0001,NaN,NaN,0,cases
1,2016-03-19,Argentina-Buenos_Aires,province,cumulative_probable_local_cases,AR0002,NaN,NaN,0,cases
2,2016-03-19,Argentina-Buenos_Aires,province,cumulative_confirmed_imported_cases,AR0003,NaN,NaN,2,cases
3,2016-03-19,Argentina-Buenos_Aires,province,cumulative_probable_imported_cases,AR0004,NaN,NaN,1,cases
4,2016-03-19,Argentina-Buenos_Aires,province,cumulative_cases_under_study,AR0005,NaN,NaN,127,cases
5,2016-03-19,Argentina-Buenos_Aires,province,cumulative_cases_discarded,AR0006,NaN,NaN,0,cases
6,2016-03-19,Argentina-CABA,province,cumulative_confirmed_local_cases,AR0001,NaN,NaN,0,cases
7,2016-03-19,Argentina-CABA,province,cumulative_probable_local_cases,AR0002,NaN,NaN,0,cases
8,2016-03-19,Argentina-CABA,province,cumulative_confirmed_imported_cases,AR0003,NaN,NaN,9,cases
9,2016-03-19,Argentina-CABA,province,cumulative_probable_imported_cases,AR0004,NaN,NaN,0,cases
10,2016-03-19,Argentina-CABA,province,cumulative_cases_under_study,AR0005,NaN,NaN,68,cases
11,2016-03-19,Argentina-CABA,province,cumulative_cases_discarded,AR0006,NaN,NaN,1,cases
12,2016-03-19,Argentina-Catamarca,province,cumulative_confirmed_local_cases,AR0001,NaN,NaN,0,cases
13,2016-03-19,Argentina-Catamarca,province,cumulative_probable_local_cases,AR0002,NaN,NaN,0,cases
14,2016-03-19,Argentina-Catamarca,province,cumulative_confirmed_imported_cases,AR0003,NaN,NaN,0,cases
15,2016-03-19,Argentina-Catamarca,province,cumulative_probable_imported_cases,AR0004,NaN,NaN,0,cases
16,2016-03-19,Argentina-Catamarca,province,cumulative_cases_under_study,AR0005,NaN,NaN,14,cases
17,2016-03-19,Argentina-Catamarca,province,cumulative_cases_discarded,AR0006,NaN,NaN,0,cases
18,2016-03-19,Argentina-Chaco,province,cumulative_confirmed_local_cases,AR0001,NaN,NaN,0,cases
19,2016-03-19,Argentina-Chaco,province,cumulative_probable_local_cases,AR0002,NaN,NaN,0,cases
20,2016-03-19,Argentina-Chaco,province,cumulative_confirmed_imported_cases,AR0003,NaN,NaN,0,cases
21,2016-03-19,Argentina-Chaco,province,cumulative_probable_imported_cases,AR0004,NaN,NaN,0,cases
22,2016-03-19,Argentina-Chaco,province,cumulative_cases_under_study,AR0005,NaN,NaN,48,cases
23,2016-03-19,Argentina-Chaco,province,cumulative_cases_discarded,AR0006,NaN,NaN,0,cases
24,2016-03-19,Argentina-Chubut,province,cumulative_confirmed_local_cases,AR0001,NaN,NaN,0,cases
25,2016-03-19,Argentina-Chubut,province,cumulative_probable_local_cases,AR0002,NaN,NaN,0,cases
26,2016-03-19,Argentina-Chubut,province,cumulative_confirmed_imported_cases,AR0003,NaN,NaN,1,cases
27,2016-03-19,Argentina-Chubut,province,cumulative_probable_imported_cases,AR0004,NaN,NaN,0,cases
28,2016-03-19,Argentina-Chubut,province,cumulative_cases_under_study,AR0005,NaN,NaN,5,cases
29,2016-03-19,Argentina-Chubut,province,cumulative_cases_discarded,AR0006,NaN,NaN,0,cases
...,...,...,...,...,...,...,...,...,...
107589,2016-06-21,United_States_Virgin_Islands,territory,confirmed_headache,VI0019,NaN,NaN,13,cases
107590,2016-06-21,United_States_Virgin_Islands,territory,confirmed_malaise,VI0020,NaN,NaN,5,cases
107591,2016-06-21,United_States_Virgin_Islands,territory,zika_no_specimen,VI0021,NaN,NaN,3,cases
107592,2016-06-28,United_States_Virgin_Islands,territory,zika_reported,VI0001,NaN,NaN,326,cases
107593,2016-06-28,United_States_Virgin_Islands-Saint_Thomas,county,zika_reported,VI0001,NaN,NaN,144,cases
107594,2016-06-28,United_States_Virgin_Islands-Saint_Croix,county,zika_reported,VI0001,NaN,NaN,173,cases
107595,2016-06-28,United_States_Virgin_Islands-Saint_John,county,zika_reported,VI0001,NaN,NaN,9,cases
107596,2016-06-28,United_States_Virgin_Islands,territory,zika_lab_positive,VI0002,NaN,NaN,29,cases
107597,2016-06-28,United_States_Virgin_Islands-Saint_Thomas,county,zika_lab_positive,VI0002,NaN,NaN,12,cases
107598,2016-06-28,United_States_Virgin_Islands-Saint_Croix,county,zika_lab_positive,VI0002,NaN,NaN,16,cases
107599,2016-06-28,United_States_Virgin_Islands-Saint_John,county,zika_lab_positive,VI0002,NaN,NaN,1,cases
107600,2016-06-28,United_States_Virgin_Islands,territory,zika_not,VI0003,NaN,NaN,252,cases
107601,2016-06-28,United_States_Virgin_Islands,territory,zika_pending,VI0004,NaN,NaN,43,cases
107602,2016-06-28,United_States_Virgin_Islands,territory,confirmed_age_under20,VI0005,NaN,NaN,4,cases
107603,2016-06-28,United_States_Virgin_Islands,territory,confirmed_age_20to39,VI0006,NaN,NaN,12,cases
107604,2016-06-28,United_States_Virgin_Islands,territory,confirmed_age_40to59,VI0007,NaN,NaN,10,cases
107605,2016-06-28,United_States_Virgin_Islands,territory,confirmed_age_over59,VI0008,NaN,NaN,3,cases
107606,2016-06-28,United_States_Virgin_Islands,territory,confirmed_age_unk,VI0009,NaN,NaN,0,cases
107607,2016-06-28,United_States_Virgin_Islands,territory,confirmed_male,VI0010,NaN,NaN,7,cases
107608,2016-06-28,United_States_Virgin_Islands,territory,confirmed_female,VI0011,NaN,NaN,22,cases
107609,2016-06-28,United_States_Virgin_Islands,territory,confirmed_fever,VI0012,NaN,NaN,2,cases
107610,2016-06-28,United_States_Virgin_Islands,territory,confirmed_acute_fever,VI0013,NaN,NaN,9,cases
107611,2016-06-28,United_States_Virgin_Islands,territory,confirmed_arthralgia,VI0014,NaN,NaN,19,cases
107612,2016-06-28,United_States_Virgin_Islands,territory,confirmed_arthritis,VI0015,NaN,NaN,13,cases
107613,2016-06-28,United_States_Virgin_Islands,territory,confirmed_rash,VI0016,NaN,NaN,18,cases
107614,2016-06-28,United_States_Virgin_Islands,territory,confirmed_conjunctivitis,VI0017,NaN,NaN,7,cases
107615,2016-06-28,United_States_Virgin_Islands,territory,confirmed_eyepain,VI0018,NaN,NaN,13,cases
107616,2016-06-28,United_States_Virgin_Islands,territory,confirmed_headache,VI0019,NaN,NaN,14,cases
107617,2016-06-28,United_States_Virgin_Islands,territory,confirmed_malaise,VI0020,NaN,NaN,5,cases
107618,2016-06-28,United_States_Virgin_Islands,territory,zika_no_specimen,VI0021,NaN,NaN,2,cases

In [2]:
data_field_filtered= data[data['data_field'].str.contains("confirmed",na=False)]
# data_field_filtered = data[data["data_field"].isin(["cumulative_confirmed_imported_cases","cumulative_confirmed_local_cases"])]
data_field_filtered


# location_filtered
# df = df.loc[~df['Type'].isin(['UnweightedBase', 'Base'])]

,report_date,location,location_type,data_field,data_field_code,time_period,time_period_type,value,unit
0,2016-03-19,Argentina-Buenos_Aires,province,cumulative_confirmed_local_cases,AR0001,NaN,NaN,0,cases
2,2016-03-19,Argentina-Buenos_Aires,province,cumulative_confirmed_imported_cases,AR0003,NaN,NaN,2,cases
6,2016-03-19,Argentina-CABA,province,cumulative_confirmed_local_cases,AR0001,NaN,NaN,0,cases
8,2016-03-19,Argentina-CABA,province,cumulative_confirmed_imported_cases,AR0003,NaN,NaN,9,cases
12,2016-03-19,Argentina-Catamarca,province,cumulative_confirmed_local_cases,AR0001,NaN,NaN,0,cases
14,2016-03-19,Argentina-Catamarca,province,cumulative_confirmed_imported_cases,AR0003,NaN,NaN,0,cases
18,2016-03-19,Argentina-Chaco,province,cumulative_confirmed_local_cases,AR0001,NaN,NaN,0,cases
20,2016-03-19,Argentina-Chaco,province,cumulative_confirmed_imported_cases,AR0003,NaN,NaN,0,cases
24,2016-03-19,Argentina-Chubut,province,cumulative_confirmed_local_cases,AR0001,NaN,NaN,0,cases
26,2016-03-19,Argentina-Chubut,province,cumulative_confirmed_imported_cases,AR0003,NaN,NaN,1,cases
30,2016-03-19,Argentina-Cordoba,province,cumulative_confirmed_local_cases,AR0001,NaN,NaN,1,cases
32,2016-03-19,Argentina-Cordoba,province,cumulative_confirmed_imported_cases,AR0003,NaN,NaN,1,cases
36,2016-03-19,Argentina-Corrientes,province,cumulative_confirmed_local_cases,AR0001,NaN,NaN,0,cases
38,2016-03-19,Argentina-Corrientes,province,cumulative_confirmed_imported_cases,AR0003,NaN,NaN,2,cases
42,2016-03-19,Argentina-Entre_Rios,province,cumulative_confirmed_local_cases,AR0001,NaN,NaN,0,cases
44,2016-03-19,Argentina-Entre_Rios,province,cumulative_confirmed_imported_cases,AR0003,NaN,NaN,0,cases
48,2016-03-19,Argentina-Formosa,province,cumulative_confirmed_local_cases,AR0001,NaN,NaN,0,cases
50,2016-03-19,Argentina-Formosa,province,cumulative_confirmed_imported_cases,AR0003,NaN,NaN,0,cases
54,2016-03-19,Argentina-Jujuy,province,cumulative_confirmed_local_cases,AR0001,NaN,NaN,0,cases
56,2016-03-19,Argentina-Jujuy,province,cumulative_confirmed_imported_cases,AR0003,NaN,NaN,0,cases
60,2016-03-19,Argentina-La_Pampa,province,cumulative_confirmed_local_cases,AR0001,NaN,NaN,0,cases
62,2016-03-19,Argentina-La_Pampa,province,cumulative_confirmed_imported_cases,AR0003,NaN,NaN,0,cases
66,2016-03-19,Argentina-La_Rioja,province,cumulative_confirmed_local_cases,AR0001,NaN,NaN,0,cases
68,2016-03-19,Argentina-La_Rioja,province,cumulative_confirmed_imported_cases,AR0003,NaN,NaN,0,cases
72,2016-03-19,Argentina-Mendoza,province,cumulative_confirmed_local_cases,AR0001,NaN,NaN,0,cases
74,2016-03-19,Argentina-Mendoza,province,cumulative_confirmed_imported_cases,AR0003,NaN,NaN,1,cases
78,2016-03-19,Argentina-Misiones,province,cumulative_confirmed_local_cases,AR0001,NaN,NaN,0,cases
80,2016-03-19,Argentina-Misiones,province,cumulative_confirmed_imported_cases,AR0003,NaN,NaN,0,cases
84,2016-03-19,Argentina-Neuquen,province,cumulative_confirmed_local_cases,AR0001,NaN,NaN,0,cases
86,2016-03-19,Argentina-Neuquen,province,cumulative_confirmed_imported_cases,AR0003,NaN,NaN,0,cases
...,...,...,...,...,...,...,...,...,...
107577,2016-06-21,United_States_Virgin_Islands,territory,confirmed_age_40to59,VI0007,NaN,NaN,9,cases
107578,2016-06-21,United_States_Virgin_Islands,territory,confirmed_age_over59,VI0008,NaN,NaN,2,cases
107579,2016-06-21,United_States_Virgin_Islands,territory,confirmed_age_unk,VI0009,NaN,NaN,0,cases
107580,2016-06-21,United_States_Virgin_Islands,territory,confirmed_male,VI0010,NaN,NaN,8,cases
107581,2016-06-21,United_States_Virgin_Islands,territory,confirmed_female,VI0011,NaN,NaN,18,cases
107582,2016-06-21,United_States_Virgin_Islands,territory,confirmed_fever,VI0012,NaN,NaN,2,cases
107583,2016-06-21,United_States_Virgin_Islands,territory,confirmed_acute_fever,VI0013,NaN,NaN,8,cases
107584,2016-06-21,United_States_Virgin_Islands,territory,confirmed_arthralgia,VI0014,NaN,NaN,18,cases
107585,2016-06-21,United_States_Virgin_Islands,territory,confirmed_arthritis,VI0015,NaN,NaN,12,cases
107586,2016-06-21,United_States_Virgin_Islands,territory,confirmed_rash,VI0016,NaN,NaN,17,cases
107587,2016-06-21,United_States_Virgin_Islands,territory,confirmed_conjunctivitis,VI0017,NaN,NaN,7,cases
107588,2016-06-21,United_States_Virgin_Islands,territory,confirmed_eyepain,VI0018,NaN,NaN,12,cases
107589,2016-06-21,United_States_Virgin_Islands,territory,confirmed_headache,VI0019,NaN,NaN,13,cases
107590,2016-06-21,United_States_Virgin_Islands,territory,confirmed_malaise,VI0020,NaN,NaN,5,cases
107602,2016-06-28,United_States_Virgin_Islands,territory,confirmed_age_under20,VI0005,NaN,NaN,4,cases
107603,2016-06-28,United_States_Virgin_Islands,territory,confirmed_age_20to39,VI0006,NaN,NaN,12,cases
107604,2016-06-28,United_States_Virgin_Islands,territory,confirmed_age_40to59,VI0007,NaN,NaN,10,cases
107605,2016-06-28,United_States_Virgin_Islands,territory,confirmed_age_over59,VI0008,NaN,NaN,3,cases
107606,2016-06-28,United_States_Virgin_Islands,territory,confirmed_age_unk,VI0009,NaN,NaN,0,cases
107607,2016-06-28,United_States_Virgin_Islands,territory,confirmed_male,VI0010,NaN,NaN,7,cases
107608,2016-06-28,United_States_Virgin_Islands,territory,confirmed_female,VI0011,NaN,NaN,22,cases
107609,2016-06-28,United_States_Virgin_Islands,territory,confirmed_fever,VI0012,NaN,NaN,2,cases
107610,2016-06-28,United_States_Virgin_Islands,territory,confirmed_acute_fever,VI0013,NaN,NaN,9,cases
107611,2016-06-28,United_States_Virgin_Islands,territory,confirmed_arthralgia,VI0014,NaN,NaN,19,cases
107612,2016-06-28,United_States_Virgin_Islands,territory,confirmed_arthritis,VI0015,NaN,NaN,13,cases
107613,2016-06-28,United_States_Virgin_Islands,territory,confirmed_rash,VI0016,NaN,NaN,18,cases
107614,2016-06-28,United_States_Virgin_Islands,territory,confirmed_conjunctivitis,VI0017,NaN,NaN,7,cases
107615,2016-06-28,United_States_Virgin_Islands,territory,confirmed_eyepain,VI0018,NaN,NaN,13,cases
107616,2016-06-28,United_States_Virgin_Islands,territory,confirmed_headache,VI0019,NaN,NaN,14,cases
107617,2016-06-28,United_States_Virgin_Islands,territory,confirmed_malaise,VI0020,NaN,NaN,5,cases

In [3]:

# location_group

data_field_filtered["country"]=data["location"]
data_field_filtered["country"]= data["location"].str.split("-", n= 1, expand=True)
                                            
#                                             
# 
data_field_filtered.info()

# data = data.groupby('domain')['ID'].nunique()

# location_filtered = data[data["location_type"]!=["territory","county"]]
# location_filtered

# location_group = zika_df.groupby("location")
# location = pd.DataFrame(location_group)
# location_group = location_group.str.split("-", n = 1, expand = True) 




# 
# print(location.to_string())

C:\Users\Dan\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

<class 'pandas.core.frame.DataFrame'>
Int64Index: 47481 entries, 0 to 107617
Data columns (total 10 columns):
report_date         47481 non-null object
location            47481 non-null object
location_type       47481 non-null object
data_field          47481 non-null object
data_field_code     47481 non-null object
time_period         0 non-null float64
time_period_type    0 non-null float64
value               47469 non-null object
unit                47481 non-null object
country             47481 non-null object
dtypes: float64(2), object(8)
memory usage: 4.0+ MB

C:\Users\Dan\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [18]:
#data_field_filtered["value"]=np.where(data_field_filtered["value"]=="NA",0,data_field_filtered["value"])
# data_field_filtered.loc[data_field_filtered["value"]!="NA"]
# data_field_filtered
data_field_filtered1= data_field_filtered[pd.notnull(data_field_filtered["value"])]
# data_field_filtered1.info() 

data_field_filtered1["value1"]= data_field_filtered1["value"].astype("int64")
data_field_filtered1
# calculated the null values
# data_field_filtered1.isnull().sum()

# data_field_filtered1["country"].value_counts()

country_df = data_field_filtered1.groupby('country')["value1"].sum().to_frame().reset_index()

country_df = country_df.rename(columns = {country_df.columns[1]: "comfirmed_cases" })
country_df

C:\Users\Dan\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

                         country  comfirmed_cases
0                      Argentina              665
1                         Brazil            25763
2                       Colombia           443745
3             Dominican_Republic             2447
4                        Ecuador             8175
5                    El_Salvador              472
6                      Guatemala             1578
7                         Mexico              565
8                      Nicaragua             4704
9                         Panama              762
10                   Puerto_Rico            44344
11  United_States_Virgin_Islands             2000

In [14]:
country_df.to_json(orient='records')

'[{"country":"Argentina","comfirmed_cases":665},{"country":"Brazil","comfirmed_cases":25763},{"country":"Colombia","comfirmed_cases":443745},{"country":"Dominican_Republic","comfirmed_cases":2447},{"country":"Ecuador","comfirmed_cases":8175},{"country":"El_Salvador","comfirmed_cases":472},{"country":"Guatemala","comfirmed_cases":1578},{"country":"Mexico","comfirmed_cases":565},{"country":"Nicaragua","comfirmed_cases":4704},{"country":"Panama","comfirmed_cases":762},{"country":"Puerto_Rico","comfirmed_cases":44344},{"country":"United_States_Virgin_Islands","comfirmed_cases":2000}]'